version: '1.41'

services:

   my_app:

      build:
         context: .
         dockerfile: wikdpstp03

      ports: 
         -  '8080'

      deploy:
        replicas: 4

      restart: always

      environement:
        - PORT=8080

      networks:
         - front-networks

      volumes:
 
       - db_data:/app/bdd.db 

   proxy:

        image: nginx:latest

        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro

        ports:
         - 8081:80*

        depends_on:
         - my_app

        networks:
         - front_network

   networks:
       front-network:
        driver: bridge

   volumes:
      db_data:
      


        